### PR TITLE
Don't require urllib3 version < 1.8

### PR DESCRIPTION
**Pull request by nelljerram**
This is needed for running Calico with the current OpenStack tip, because http://git.openstack.org/cgit/openstack/requirements/tree/global-requirements.txt has

```
urllib3>=1.8.3
```

This shows up particularly when using devstack, because Calico, python-etcd and OpenStack projects are all then installed from source.  But it might bite also with some pieces being package-installed - I don't know.

We had an issue for a while at https://github.com/Metaswitch/calico/issues/419, about lifting our version cap, but this was eventually closed because there was no clear reason for it.  But now it appears we do have a clear reason.  @fasaxc tells me that he expects that we may hit corner case issues when lifting this cap, but that the mainline should work - and indeed, my testing so far confirms that the mainline does work.  I guess it would be good to know more about those corner case issues, so we can devise a plan for addressing them.

### CODE REVIEW

**Comment by nelljerram** [comment]
@Lukasa @fasaxc - Would one of you be happy to be assigned to review this?

**Comment by fasaxc** [comment]
@neiljerram Sadly, lifting the cap requires more than just removing it from the file.  The exception hierarchy of urllib3 changed substantially between the versions and python-etcd isn't expecting the new exceptions.  We need to examine which exceptions they catch and which we catch and make sure that we do the right thing.

I think we now catch the root exceptions in `fetcd.py` so we're probably in reasonably good shape but we need to audit that code to make sure that we're not going to log spammy errors for expected conditions.

**Comment by Lukasa** [comment]
Yeah, @fasaxc is right here, there's a bit more work that has to get done here.

Hopefully it might have been done upstream!

**Comment by beddari** [comment]
So what is the current status of this? Our RDO-based Openstack systems are using python-urllib3 1.10.2 ... and although we can do packaged virtualenvs we'd rather help get this properly sorted out ...

**Comment by beddari** [comment]
This issue should probably be closed with a note that it should now be possible to use a newer urllib3 but no automated testing is done yet, per a comment on irc from @fasaxc 

https://github.com/projectcalico/python-etcd/blob/master/debian/changelog#L4

**Comment by fasaxc** [comment]
This PR appears to be out-of-date and it's pulling in a lot of unexpected commits.

**Pull request closed without merging**
